name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest playwright
        playwright install

    - name: Run Unit Tests
      run: pytest tests/unit

    - name: Run Integration Tests
      run: pytest tests/integration

    - name: Run End-to-End Tests
      run: pytest tests/e2e
