name: CI/CD

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
         python-version: '3.10'
         
     - uses: actions/cache@v3
       with:
         path: |
           venv
           ~/.cache/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-

     - name: Install dependencies
       run: |
         pip install -r requirements.txt
         pip install pytest playwright
         playwright install

     - name: Run tests
       run: |
         source venv/bin/activate
         pytest tests/unit/ --cov=src --junitxml=test-results/junit.xml
         pytest tests/integration/
         pytest tests/e2e/

 security:
   needs: test
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     
     - name: Build image
       run: docker build -t app:test .
     - name: Install Trivy
       run: |
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.67.2/trivy_0.67.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.67.2_Linux-64bit.deb
     
     - name: Run Trivy vulnerability scanner
       uses: aquasecurity/trivy-action@master
       with:
         image-ref: 'app:test'
         format: 'table'
         exit-code: '1'
         ignore-unfixed: true
         severity: 'CRITICAL,HIGH'
         ignorefile: .trivyignore

 deploy:
   needs: security
   if: github.ref == 'refs/heads/main'
   runs-on: ubuntu-latest
   environment: production
   steps:
     - uses: actions/checkout@v4
     
     - uses: docker/setup-buildx-action@v3
     
     - uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         
     - uses: docker/build-push-action@v5
       with:
         push: true
         tags: |
           domsil12/assignment8:latest
           domsil12/assignment8:${{ github.sha }}
         platforms: linux/amd64,linux/arm64
         cache-from: type=registry,ref=domsil12/assignment8:cache
         cache-to: type=inline,mode=max
